# License: LGPL-3.0-or-later
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      development_minor:
        dependency-type: development
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "storybook"
          - "@storybook/*"
      development_major:
        dependency-type: development
        update-types:
          - major
        exclude-patterns:
          - "storybook"
          - "@storybook/*"
      storybook-minor:
        patterns:
          - "storybook"
          - "@storybook/*"
        update-types:
          - "patch"
          - "minor"
      storybook-major:
        patterns:
          - "storybook"
          - "@storybook/*"
        update-types:
          - major
      production_minor:
        dependency-type: production
        update-types:
          - minor
          - patch
      production_major:
        dependency-type: production
        update-types:
          - major

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    allow:

    groups:
      minor-storybook-updates:
        update-types:
          - "patch"
          - "minor"
      major-storybook-updates:
        update-types:
          - "major"


